const actionType={
    MARK_NOTIFICATION_AD_READ:" MARK_NOTIFICATION_AD_READ",
    MARK_NOTIFICATION_All_READ:" MARK_NOTIFICATION_All_READ",
    START_LOGIN:"START_LOGIN",
    LOGIN_SUCCSSED:"LOGIN_SUCCSSED",
    LOGIN_FAIL:"LOGIN_FAIL"

}

export default actionType
